apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-react
  labels:
    app: sample-react
spec:
  replicas: 2 #The number of pods to be created in the Kubernetes cluster for the React.js application container
  selector:
    matchLabels:
      app: sample-react
  template:
    metadata:
      labels:
        app: sample-react
    spec:
      containers:
      - name: sample-react #The name of the react.js application container
        image: h264/sample-react:latest #The Docker image for building the React.js application container
        imagePullPolicy: Always
        ports:
        - containerPort: 3000 #The port for the React.js application   container
